services:
  db:
    build:
      context: .
      dockerfile: .docker/postgres.Dockerfile
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '${EXTERNAL_DB_PORT:-5432}:5432'
  redis:
    image: redis:7-alpine
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - ./tmp/redis:/data
    restart: unless-stopped
  app:
    build:
      context: .
      dockerfile: .docker/app.Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p ${RAILS_PORT:-3000} -b '0.0.0.0'"
    stdin_open: true
    tty: true
    volumes:
      - '.:/code'
    ports:
      - '${RAILS_PORT:-3000}:${RAILS_PORT:-3000}'
    environment:
      - 'PORT=${RAILS_PORT:-3000}'
      - 'REDIS_URL=redis://redis:6379/0'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - 'db'
      - 'redis'
    networks:
      - default
      - elastic
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    environment:
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - xpack.security.enabled=false
      - logger.level=INFO
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./tmp/elasticsearch:/usr/share/elasticsearch/data
      - ./log/elasticsearch:/usr/share/elasticsearch/logs
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.1
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - LOGGING_DEST=file
      - LOGGING_DEST_FILE=/usr/share/kibana/logs/kibana.log
    volumes:
      - ./log/kibana:/usr/share/kibana/logs
    depends_on:
      - elasticsearch
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
