services:
  db:
    build:
      context: .
      dockerfile: .docker/postgres.Dockerfile
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432'
  app:
    build:
      context: .
      dockerfile: .docker/app.Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    volumes:
      - '.:/code'
    ports:
      - '3000'
    environment:
      - '3000'
    depends_on:
      - 'db'
