name: Rails CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        ruby-version: [3.3.6]

    steps:
      - name: Check out Repository
        uses: actions/checkout@v4

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install PostgreSQL Dependencies
        run: sudo apt-get update && sudo apt-get install -y libpq-dev

      - name: Install Gems
        run: bundle install

      - name: Set Up Database
        run: |
          cp config/database.github-actions.yml config/database.yml
          bundle exec rake db:create
          bundle exec rake db:migrate
          bundle exec rake db:schema:load
          bundle exec rake db:seed
        env:
          RAILS_ENV: test

      - name: Run Security Checks
        run: |
          bundle exec bundler-audit --update
          bundle exec brakeman -q -w2

      - name: Run Fasterer
        run: bundle exec fasterer

      - name: Run Rubocop
        run: bundle exec rubocop --parallel

      - name: Run RSpec
        run: bundle exec rspec
